//
// Created by william on 9/10/2026.
//

#ifndef SIMULATIONENGINE_POSESSIONSTATE_H
#define SIMULATIONENGINE_POSESSIONSTATE_H

enum PosessionState {
  INBOUNDING,
  ESTABLISHED,
  LOOSE_BALL,
  DEAD_BALL
};
#endif //SIMULATIONENGINE_POSESSIONSTATE_H