//
// Created by william on 9/10/2026.
//

#ifndef SIMULATIONENGINE_SCORESITUATION_H
#define SIMULATIONENGINE_SCORESITUATION_H

enum ScoreSituation {
  TIED,

  CLOSE_LEADING,
  LEADING,
  BLOWOUT_LEADING,

  CLOSE_TRAILING,
  TRAILING,
  BLOWOUT_TRAILING
};
#endif //SIMULATIONENGINE_SCORESITUATION_H